tap "homebrew/bundle"
tap "buo/cask-upgrade"

brew "mas"
brew "git"
brew "fzf"
brew "ripgrep"
brew "tree"
brew "node@18"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "tmux"
brew "bat"
brew "neovim"
brew "lazygit"
brew "php"
brew "composer"
brew "mysql"
brew "lynx"

cask "spotify"
cask "font-ubuntu-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-fantasque-sans-mono-nerd-font"
cask "visual-studio-code"
cask "mattermost"
cask "microsoft-teams"
cask "kitty"
cask "iterm2"
cask "docker"
cask "1password"
cask "firefox"
cask "google-chrome"
cask "qutebrowser"
cask "obsidian"
cask "bartender"
cask "tableplus"

mas "Tailscale", id: 1475387142
mas "RunCat", id: 1429033973
mas "1Blocker - Ad Blocker", id: 1365531024
mas "TabBack för Safari", id: 1660506599
