tap "homebrew/bundle"
tap "buo/cask-upgrade"

brew "mas"
brew "git"
brew "fzf"
brew "ripgrep"
brew "tree"
brew "node@18"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "starship"
brew "tmux"
brew "bat"
brew "neovim"
brew "lazygit"
brew "php"

cask "spotify"
cask "font-ubuntu-mono-nerd-font"
cask "visual-studio-code"
cask "mattermost"
cask "raycast"
cask "microsoft-teams"
cask "kitty"
cask "docker"
cask "1password"
cask "firefox"
cask "google-chrome"
cask "obsidian"

mas "Tailscale", id: 1475387142
mas "RunCat", id: 1429033973
