#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS
  today=$(date +"%Y-%m-%d")
  tomorrow=$(date -v+1d +"%Y-%m-%d")
  yesterday=$(date -v-1d +"%Y-%m-%d")
else
  # Linux
  today=$(date +"%Y-%m-%d")
  tomorrow=$(date -d "tomorrow" +"%Y-%m-%d")
  yesterday=$(date -d "yesterday" +"%Y-%m-%d")
fi

file="$SECOND_BRAIN/Journal/$today.md"
cd "$SECOND_BRAIN" || exit

new_note() {
  touch "$file"

  # Format the file with the daily template
  cat <<EOF >"$file"
# $today

[[$yesterday]] - [[$tomorrow]]

## Habits

- [ ] Yoga
- [ ] Strength training
- [ ] Running

## Log
EOF

}

# If the daily note does not exist, create a new one.
# this uses the test command with the -f flag.
if [ ! -f "$file" ]; then
  echo "File does not exist, creating new daily note."
  new_note
fi

# Open the daily note at the bottom of the file in insert mode and run NoNeckPain to make it center
nvim '+ normal Gzzo' "$file" -c :NoNeckPain
